import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ScriptLoader from './components/utils/fontawesome'; // fontawesome
import { SupabaseProvider } from './components/utils/SupabaseProvider'; // Import the Supabase provider

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const Minecraftia = localFont({
  src: "./fonts/Minecraftia.ttf",
  variable: "--font-minecraftia",
  weight: "100 900",
});

const Poppins = localFont({
  src: "./fonts/Poppins-SemiBold.ttf",
  variable: "--font-poppins",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Komako 🐈",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Minecraftia.variable} ${Poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <SupabaseProvider>
          <Navbar />
          {children}
          <Footer />
        </SupabaseProvider>
        <ScriptLoader />
      </body>
    </html>
  );
}
