// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ScriptLoader from './components/utils/fontawesome'; // fontawesome
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]"; // Ensure correct import path
import ClientSessionProvider from "./components/utils/SessionProvider"; // Import the client-side provider
import Login from "./Login";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Komako 🐈",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <ClientSessionProvider session={session}>
          <Navbar />
          {children}
          <Footer />
        </ClientSessionProvider>
        <ScriptLoader />
      </body>
    </html>
  );
}